<center>
<div style="padding:15px;" >
<a href="http://www.turismoderiotorto.com/">
<img src= "/img/ads/chouza_feriapeq.gif" />
<!-- <img src= "/img/ads/chouza_generpeq.gif" /> -->
</a>
</div>

<br>
<?php 

$hoxe 		= date("Ymd");
$dataLimite = '20130422';
if ($hoxe < $dataLimite)
{
	echo '<p>Hello World</p>'; 
	proba
}

?> 




<div style="padding:15px;" >
<a href="http://chuza.gl/equipa/index.php?page=afiliate">
<img src= "/img/ads/afiliarChuza.jpg" />

</a>

</div>
</center>