<center>
<div style="padding:15px;" >
<a href="http://www.turismoderiotorto.com/">
<img src= "/img/ads/chouza_feriapeq.gif" />
<!-- <img src= "/img/ads/chouza_generpeq.gif" /> -->
</a>
</div>

<br>

$hoxe 		= date("Ymd");
$dataLimite = '20130402';
if ($hoxe < $dataLimite)
{
	proba
}


<div style="padding:15px;" >
<a href="http://chuza.gl/equipa/index.php?page=afiliate">
<img src= "/img/ads/afiliarChuza.jpg" />

</a>

</div>
</center>